### ISSUE TITLE
Hardcoded Yarn references

### ISSUE THREAD

**Issue by AndreasNasman** [ty-ras/meta#11]
There are some hardcoded Yarn references in the `package.json` files that cause problems if you opt for another package manager (and don't have Yarn installed).

E.g., there files for `be-and-fe`:
- [backend/package.json](https://github.com/ty-ras/meta/blob/main/start/templates/io-ts/be-and-fe/components/backend/package.json#L20)
- [frontend/package.json](https://github.com/ty-ras/meta/blob/main/start/templates/io-ts/be-and-fe/components/frontend/package.json#L26)
- [protocol/package.json](https://github.com/ty-ras/meta/blob/main/start/templates/io-ts/be-and-fe/components/protocol/package.json#L17)

**Comment by AndreasNasman** [comment]
Would be nice if there was a standardized environment variable for whatever package manager you use, or that everyone used the same (like `cargo` in Rust land) 😄

**Comment by stazz** [comment]
Good catch, these hardcoded yarn references need to be replaced if target package manager is something else than yarn. Shouldn't be a huge task, after current one is completed. 👍

**Comment by stazz** [comment]
This is now fixed in version `0.13.4` 👍
