### ISSUE TITLE
Project root is missing '.gitignore'

### ISSUE THREAD

**Issue by dusan-turajlic** [ty-ras/meta#22]
When using the `npx @ty-ras/start@latest` it creates everyhting as it should. But the root is missing `.gitignore`. 

This is really annoying because if you open it and want to commit all the newly created files and do something like
```shell
git commit -am "Initial commit"
```

You will also commit the `node_modules` directory if you opted to install dependencies before making this commit.

**Comment by stazz** [comment]
Very good point - I'll fix this once I get to 2.0 version of this 👍

**Comment by stazz** [comment]
Should be fixed in `2.0.1` now 👍
